services:
  servicepulse:
    image: servicepulse
    container_name: servicepulse
    build: .
    env_file:
      - .env
    ports:
      - "8093:8093"
    volumes:
      - ./log:/app/log
      - ./config:/app/config
    restart: always
